/*Scope and Comments*/
public class topic9 {
	public String print()
	{
		return "1. Local variables, Variables that are declared inside a method are called local vairables.\n"
				+ "2. A local variables`s scope begins at the variables`s declaration and ends at the end of the method in which the variable is declared.\n"
				+ "3. \"Cannot resovle symbol.\". It means that the compiler has encountered a name for whcih it cannot determin a meaning.\n"
				+ "4. Single-Line Comments, you simply place two forward slashes (//).\n"
				+ "5. Multiline Comments,  it starts with /* and end with */. \n"
				+ "6. Documentation commment, any comment htat starts with /** and end with */. \n "
				+ "7. The documentation comment could be generated by \"javadoc *.java\". Serveral documentation files will be created in the same directory as the source code file. Clikc \"index.html\" to open it with Internet Explorer.\n";
	}
}
